### ISSUE TITLE
rounding up vs. rounding down

### ISSUE THREAD

**Issue by benibela** [nigeltao/parse-number-fxx-test-data#1]
I have run these tests on [someone's double parser](https://github.com/BeRo1985/pasdblstrutils/issues/2) which discovered thousands of wrongly parsed numbers

But on closer examination, that parser still finds the nearest double number. Just there are two nearest numbers.
E.g. 9008309105029287 has  9008309105029288 (+1) and 9008309105029286 (-1)

Is it really important to return the larger one?

**Comment by nigeltao** [comment]
If there's a tie then we use standard IEEE 754 round-to-even rules.

https://nigeltao.github.io/blog/2020/eisel-lemire.html#round-to-even has some examples.

At least, that's what I remember doing. Let me know if there's still a discrepancy.

**Comment by nigeltao** [comment]
> Is it really important to return the larger one?

It is important that parsing text-based formats to `float64` values is deterministic, across different libraries. As a silly example, it wouldn't work if a message like "send Bob 3.5 million dollars" was rounded by Bob to 4 million but rounded by me to 3 million, even though both are equally distant.

**Comment by benibela** [comment]
>If there's a tie then we use standard IEEE 754 round-to-even rules.

But floats with positive exponent are always even.  Either direction would be round-to-even 

>https://nigeltao.github.io/blog/2020/eisel-lemire.html#round-to-even has some examples.

Guess that explains it. Some numbers are more even than even
